blackbaud/sky-api-docs

content/api/entity-reference/index.html, content/api/entity-reference/peer-to-peer/index.html, content/support/changelog/index.md, content/support/changelog/peer-to-peer/index.md, includes/basics/baseurl.md, stache.yml
* Adds the Entity Reference page to the main navigation and publishes the Peer-to-Peer entity reference page.
* Adds Peer-to-Peer changelog with initial announcement entry
* Adds Peer-to-Peer to Basics baseurl table
=> Peer-to-Peer Beta

content/docs/authorization/auth-code-flow/index.md
fix bug on step 6 of Auth Code Flow page
=> add v1 to sample request

content/api/entity-reference/index.md, stache.yml, static/assets/js/entity-reference/app.1.1.js
=> Revert SkyUX version update

includes/basics/ratelimits.md
=> Fix typo in ratelimits.md

package.json, stache.deploy.yml
- Bumping the docs version to 1.0.0
=> Release 1.0.0

content/api/entity-reference/accounts-payable/index.html, content/api/entity-reference/gift/index.html, content/support/changelog/gift/index.md
Now also includes gift aid branch changes
=> Feature entity ref two column tables

content/api/entity-reference/gift/index.html, content/support/changelog/constituent/index.md
- New address dates changelog
- Gift aid amount and qualification status on gift split entity reference
=> address changelog and split gift aid entity ref

content/api/entity-reference/gift/index.html, content/support/changelog/constituent/index.md, content/support/changelog/gift/index.md, stache.yml
I merged rob's and my old branches into here without the outdated develop branch history. Will be requesting to release once relationship patch hits cdev
=> Gift payments and subtypes, and Constituent relationship patch

package.json
Fix for travis builds: https://github.com/sass/node-sass/issues/2100
=> added request as a hard dependency at version 2.81.0

content/support/changelog/gift/index.md, stache.yml
Gift POST
Gift List Constituent id filter
=> Gift changelog

content/support/changelog/ap/index.md, content/support/changelog/constituent/index.md, content/support/changelog/fundraising/index.md, content/support/changelog/gift/index.md, content/support/changelog/gl/index.md, content/support/changelog/opportunity/index.html, content/support/changelog/shared/index.md, content/support/changelog/treasury/index.md
should be changelog gift **batch** number, but left it named as is.
=> Changelog gift branch number

content/api/entity-reference/constituent/index.html, content/support/changelog/constituent/index.md, stache.yml
Changelog for current outgoing release. Please do not merge to prod until we confirm the API has been successfully deployed in prod.
=> Notes list changelog

static/assets/js/entity-reference/app.1.2.js
updating entity reference to sort by display name and then name if no display name is present
=> updating entity reference to sort by display name

content/support/issues/index.md
=> Add short issue summary

static/assets/js/entity-reference/k12.json
+ Copied swagger output into k12.json in order to update entity reference
=> Updated k12 entity ref with latest Swagger

content/api/entity-reference/k12/index.html
+ Changed **last-updated-date** field to _January 8, 2018_ from _December 8, 2017_
=> updated the publish date field for entity reference

content/api/entity-reference/k12/index.html, static/assets/js/entity-reference/k12.json
+ Changed the entity reference 'last updated date' from 'November 8, 2017' to 'January 8, 2018'
=> Updated k12 entity reference 'last updated date'

static/assets/js/entity-reference/app.1.2.js, static/assets/views/entities.html
A toLower was added, but the string being compared to was still in uppercase
=> fixed the loading of dev swagger when flag supplied

content/api/entity-reference/constituent/index.html, content/support/changelog/constituent/index.md
Not currently ready to be merged. Will notify and update this PR when ready. John mentioned he would be going out of town so I added Lindsey.
=> Release for 02/02/2018

content/api/entity-reference/constituent/index.html, content/api/entity-reference/fundraising/index.html, content/api/entity-reference/gift/index.html, content/api/entity-reference/opportunity/index.html
Updating last-updated dates on entity references based on most recent dates where changelog entries called out entity changes.
=> Update last-updated dates for entity references.

content/api/entity-reference/k12/index.html, static/assets/js/entity-reference/k12.json
**Changelog:**
- Updated _js/entity-reference/k12.json_ with the latest entity ref JSON output
- Updated **Last Updated Date** in _entity-reference/k12/index.html_
=> Updated K12 entity reference

content/api/entity-reference/k12/index.html, includes/basics/response.md, static/assets/js/entity-reference/k12.json
**Changelog**:
- Updated js/entity-reference/k12.json with the latest entity ref JSON output
- Updated Last Updated Date in entity-reference/k12/index.html
=> Update K12 Entity Reference

content/api/entity-reference/k12/index.html, static/assets/js/entity-reference/k12.json
**Changelog**:
* Updated **K12.json** to contain the latest Swagger JSON output featuring the name change from "**K12**" to "**School**"
* Changed _/entity-reference/k12/**index.html**_ to contain name changes from '**K12**" to "**School**"
=> Change 'K12' to 'School' in SKY entity reference

content/support/issues/index.md
https://blackbaud.visualstudio.com/Products/_workitems/edit/966549
=> adding address list issue

content/support/changelog/index.md, content/support/changelog/payments/index.md, stache.yml
Not showing in the side navigation nor the main changelog page for now.
=> Adding payments API changelog

static/assets/js/entity-reference/app.1.2.js, static/assets/views/entities.html, static/assets/views/entitytable.html, static/assets/views/operationentities.html
Refactoring current entity reference to create a new directive for generating property tables for the endpoint reference page.
=> Feature swagger properties table operations

content/support/changelog/constituent/index.md, stache.yml
=> Post physical attachments

content/support/changelog/school/index.md, stache.yml
Updated:
- Added new School API endpoints \content\support\changelog\school\ **index.md**
- Updated **Stache.yml** with new global links to School API endpoints
=> Updates to the School API changelog

content/docs/getting-started/payments/index.md
After discussing with SKY API team, we decided it would be helpful for confirmation to have the user's name and org name.
=> Updating Getting Startged to ask for name and org.

content/docs/getting-started/payments/index.md
Added note to payments getting started guide that the user needs to be invited to the environment before the BBMS shows up in drop down.
=> Added note to payments getting started guide

content/support/changelog/school/index.md, stache.yml
**Updates**:
* Updated the \content\support\changelog\school\index.md file with new changelog entries
* Updated **Stache.yml** with new global links to School API endpoint pages
=> School API Changelog Updates

content/docs/code/auth-code-flow/nodejs/index.md
Corrected "Authroize" to "Authorize"
=> Typo correction line 299
